# Generated by Django 5.2.8 on 2026-01-15 23:26

import django.db.models.deletion
import django.utils.timezone
import rejs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rodzaj', models.CharField(choices=[('wplata', 'Wpłata'), ('zwrot', 'Zwrot'), ('payu', 'payu')], default=('zwrot', 'Zwrot'), max_length=7)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('rodzaj_id', models.CharField(blank=True, max_length=64, null=True)),
                ('zrodlo_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Wpłata',
                'verbose_name_plural': 'Wpłaty',
            },
        ),
        migrations.AlterModelOptions(
            name='rejs',
            options={'verbose_name': 'Rejs', 'verbose_name_plural': 'Rejsy'},
        ),
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AddField(
            model_name='rejs',
            name='aktywna_rekrutacja',
            field=models.BooleanField(default=True, verbose_name='aktywna rekrutacja'),
        ),
        migrations.AddField(
            model_name='rejs',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='rejs',
            name='zaliczka',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='adres',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_urodzenia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data urodzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_zgloszenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='kod_pocztowy',
            field=models.CharField(default='', verbose_name='kod pocztowy'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='miejscowosc',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='obecnosc',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=3, verbose_name='uczestnictwo w zobaczyć morze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='plec',
            field=models.CharField(choices=[('kobieta', 'kobieta'), ('mezczyzna', 'mężczyzna'), ('inna', 'inna')], default='inna', max_length=10, verbose_name='płeć'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rodo',
            field=models.BooleanField(default=True, help_text='zgadzam się na przetwarzanie danych osobowych zgodnie z polityką prywatności zobaczyć morze.', verbose_name='zgoda na przetwarzanie danych osobowych'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rola',
            field=models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty'), ('starszy-oficer', 'starszy oficer')], default='ZALOGANT', max_length=25),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rozmiar_koszulki',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 's'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=5, verbose_name='rozmiar koszulki'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='status',
            field=models.CharField(choices=[('Niezakwalifikowany', 'Niezakwalifikowany'), ('Zakwalifikowany', 'Zakwalifikowany'), ('Odrzucone', 'Odrzucone')], default='Niezakwalifikowany', max_length=20),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='uwagi',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='wzrok',
            field=models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący'), ('lekko-slabo-widzacy', 'lekko słabo widzący'), ('bardzo-slabo-widzacy', 'bardzo słabo widzący'), ('prawie-niewidzacy', 'prawie niewidomy')], default=('WIDZI', 'widzący'), max_length=25, verbose_name='Status wzroku'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='do',
            field=models.DateField(verbose_name='data do'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='koniec',
            field=models.CharField(max_length=200, verbose_name='port końcowy'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='od',
            field=models.DateField(verbose_name='data od'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='start',
            field=models.CharField(max_length=200, verbose_name='port początkowy'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='imie',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='nazwisko',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='telefon',
            field=models.CharField(max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.CreateModel(
            name='Dane_Dodatkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poz1', rejs.models.EncryptedTextField(default='12345678900', max_length=13, verbose_name='pesel')),
                ('poz2', rejs.models.EncryptedTextField(choices=[('paszport', 'paszport'), ('dowod-osobisty', 'dowód osobisty')], default=('paszport', 'paszport'), max_length=14, verbose_name='typ dokumentu')),
                ('poz3', rejs.models.EncryptedTextField(default='ABC123', verbose_name='numer dokumentu')),
                ('zgloszenie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dane_dodatkowe', to='rejs.zgloszenie')),
            ],
            options={
                'verbose_name': 'dane dodatkowe',
                'verbose_name_plural': 'dane dodatkowe',
                'permissions': [('export_sensitive_data', 'Może eksportować dane wrażliwe do raportów')],
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tytul', models.CharField(default='nowe ogłoszenie', max_length=100, verbose_name='Tytuł')),
                ('text', models.TextField(default='krótka informacja o rejsie', verbose_name='Tekst')),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenia', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscPayU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payu_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(choices=[('zaliczka', 'Zaliczka'), ('reszta', 'Reszta')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Nowa'), ('PENDING', 'W toku'), ('COMPLETED', 'Zakończona'), ('FAILED', 'Błąd')], default='NEW', max_length=20)),
                ('utworzona', models.DateTimeField(auto_now_add=True)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platnosci_payu', to='rejs.zgloszenie')),
            ],
        ),
        migrations.CreateModel(
            name='Wachta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wachty', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Wachta',
                'verbose_name_plural': 'Wachty',
            },
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='wachta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czlonkowie', to='rejs.wachta'),
        ),
        migrations.AddConstraint(
            model_name='zgloszenie',
            constraint=models.UniqueConstraint(fields=('rejs', 'imie', 'nazwisko', 'email'), name='unique_zgloszenie_na_rejs_dla_osoby'),
        ),
        migrations.AddField(
            model_name='wplata',
            name='zgloszenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wplaty', to='rejs.zgloszenie'),
        ),
    ]
