# Generated by Django 5.2.8 on 2026-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0002_wplata_alter_rejs_options_alter_zgloszenie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejs',
            name='aktywna_rekrutacja',
        ),
        migrations.AddField(
            model_name='rejs',
            name='blokada',
            field=models.BooleanField(default=False, verbose_name='Ręczna blokada rekrutacji'),
        ),
        migrations.AddField(
            model_name='rejs',
            name='liczba_miejsc',
            field=models.PositiveIntegerField(default=20, verbose_name='Liczba miejsc na rejs'),
        ),
        migrations.AddField(
            model_name='rejs',
            name='originator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizator '),
        ),
    ]
