# Generated by Django 5.2.8 on 2025-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0010_remove_wplata_finanse_wplata_rodzaj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='rola',
            field=models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty')], default='ZALOGANT', max_length=25),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='do',
            field=models.DateField(verbose_name='data do'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='koniec',
            field=models.CharField(max_length=200, verbose_name='port końcowy'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='od',
            field=models.DateField(verbose_name='data od'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='start',
            field=models.CharField(max_length=200, verbose_name='port początkowy'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='wzrok',
            field=models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący')], default=('WIDZI', 'widzący'), max_length=15),
        ),
    ]
