# Generated by Django 5.2.8 on 2026-01-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0021_alter_zgloszenie_adres_alter_zgloszenie_miejscowosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='rozmiar_koszulki',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 's'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=5, verbose_name='rozmiar koszulki'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='uwagi',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
